config/routes.rb
Rails.application.routes.draw do
  resources :gamers do
    member do
      get :friends, :blocks
    end
  end

  resources :friendships,       only: [:create, :destroy]
  resources :requests, only: [:create, :destroy]
  resources :blocks, only: [:create, :destroy]
  resources :gamers, only: [:index, :show, :update, :edit]
  resources :gamers do
    resources :comments
    patch :promote, on: :member
  end

  resources :platforms, only: [:show, :edit, :update]
  resources :games do
    resources :desires, only: [:create, :update, :destroy] do
      patch :accept, on: :member
    end
    patch :rent_back, on: :member
  end
  resources :desires, only: [:index, :destroy, :show]
  resources :titles, only: [:index, :show, :edit, :update]
  resources :queries, only: [:index, :show, :new, :create]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :get_gamers
  before_action :get_games
  before_action :get_titles

  def index
  end

  private
    def get_gamers
      @gamers = User.order("id DESC").limit(3)
    end

    def get_games
      @games = Game.order("id DESC").limit(6).includes(:game_info)
    end

    def get_titles
      @titles = GameInfo.order("id DESC").limit(6)
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_show_gamers.html.erb
<div class="row">
  <% for gamer in @gamers %>
  <div class="col s12 l4">
    <div class="card blue-grey darken-1">
      <div class="card-profile white-text">
        <% hideProfile = (current_user != gamer) && !gamer.visibility %>
        <div class="valign-wrapper">
          <% if gamer.photo.blank? %>
            <%= image_tag "no_photo.jpg", class: "circle responsive-img activator card-profile-image" %>
          <% else %>
            <img src="<%= gamer.photo %>" alt="Profile photo" class="circle responsive-img activator card-profile-image">
          <% end %>
          <a class="btn-floating activator waves-effect waves-light darken-2 right">
            <i class="material-icons">expand_less</i>
          </a>
        </div>
        <span class="card-title activator white-text darken-3">
          <%= (hideProfile || gamer.name.blank?) ? "Anomymous" : gamer.name.split.map(&:capitalize).join(" ") %>
        </span>
        <p><%= hideProfile ? "_____" : gamer.email %></p>
        <p><%= (hideProfile || gamer.city.blank?) ? "World" : gamer.city %></p>
      </div>

      <div class="card-reveal">
        <span class="card-title grey-text">
          <%= (hideProfile || gamer.name.blank?) ? "Anomymous" : gamer.name.split.map(&:capitalize).join(" ") %>
          <a class="btn-floating activator waves-effect waves-light darken-2 right">
            <i class="material-icons">expand_more</i>
          </a>
        </span>
        <div class="valign-wrapper"><i class="material-icons">email</i> <%= hideProfile ? "_____" : gamer.email %> </div>
        <div class="valign-wrapper">
          <i class="material-icons">phone</i>
          <%= (hideProfile || gamer.phone.blank?) ? "_________" : gamer.phone %>
        </div>
        <div class="valign-wrapper">
          <i class="material-icons">star_half</i>
          <%= gamer.avg_vote %>
        </div>
      </div>

      <div class="card-action">
        <% if can? :read, gamer %>
          <%= link_to "Visit profile", gamer_path(gamer) %>
        <% else %>
          <%= link_to "Log in to view more", new_user_session_path %>
        <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/welcome/_show_games.html.erb
<% caption_align = ['center-align', 'left-align', 'right-align'] %>

<div class="row center-align">
  <h4><em>Lastest games added</em></h4>
</div>

<div class="slider">
 <ul class="slides">
  <% for game in @games %>
    <li>
      <% if game.game_info.cover.blank? %>
        <%= image_tag "game_no_cover.jpg"%>
      <% else %>
        <img src="<%= game.game_info.cover.gsub(/t_thumb/, 't_720p') %>" alt="Photo of the game"/>
      <% end %>
      <div style="opacity: 0.8">
        <div class="caption card-panel grey lighten-1 <%= caption_align[1+rand(3)] %>">
          <h3 class="black-text"><em><%= game.game_info.name %></em></h3>
          <% if can? :read, game %>
            <h5 class="light blue-text text-darken-3"><%= link_to 'Show the game', game_path(game) %></h5>
          <% else %>
            <h5 class="light blue-text text-darken-3"><%= link_to 'Signin for more', new_user_session_path %></h5>
          <% end %>
        </div>

      </div>
    </li>
   <% end %>
  </ul>
</div>

app/views/welcome/_show_titles.html.erb
<% caption_align = ['center-align', 'left-align', 'right-align'] %>

<div class="row center-align">
  <h4><em>Lastest titles added</em></h4>
</div>

<div class="slider">
 <ul class="slides">
  <% for title in @titles %>
    <li>
      <% if title.cover.blank? %>
        <%= image_tag "game_no_cover.jpg"%>
      <% else %>
        <img src="<%= title.cover.gsub(/t_thumb/, 't_720p') %>" alt="Photo of the game"/>
      <% end %>
      <div style="opacity: 0.8">
        <div class="caption card-panel grey lighten-1 <%= caption_align[1+rand(3)] %>">
          <h3 class="black-text"><em><%= title.name %></em></h3>
          <% if can? :read, title %>
            <h5 class="light blue-text text-darken-3"><%= link_to 'Show the title', title_path(title) %></h5>
          <% else %>
            <h5 class="light blue-text text-darken-3"><%= link_to 'Signin for more', new_user_session_path %></h5>
          <% end %>
        </div>

      </div>
    </li>
   <% end %>
  </ul>
</div>

app/views/welcome/index.html.erb
<h2 class="center-align">
  <% if user_signed_in? && current_user.name? %>
    Welcome <%= current_user.name.split[0]%>!
  <% else %>
    Welcome to GameExchange!
  <% end %>
</h2>

<div class="row">
  <div class="col s12">
    <div class="row">
      <% if @games.blank? %>
      <div class="row center-align">
        <h4><em>No games to show</em></h4>
      </div>
      <% else %>
        <%= render "show_games" %>
        <div class="row">
          <div class="col s12 center-align" style="margin-top: 16px">
            <%= link_to 'Show all games catalog', games_path, class: 'waves-effect waves-light btn-large' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <% if @titles.blank? %>
      <div class="row center-align">
        <h4><em>No title to show</em></h4>
      </div>
      <% else %>
        <%= render "show_titles" %>
        <div class="row">
          <div class="col s12 center-align" style="margin-top: 16px">
            <%= link_to 'Show all titles', titles_path, class: 'waves-effect waves-light btn-large' %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row">
      <% if @gamers.blank? %>
      <div class="row center-align">
          <em><h4>No gamers to show</h4></em>
      </div>
      <% else %>
      <div class="row center-align">
        <h4><em>Lastest gamers</em></h4>
      </div>
        <%= render "show_gamers" %>
        <div class="col s12 center-align">
          <%= link_to 'Show all gamers', gamers_path, class: 'waves-effect waves-light btn-large' %>
        </div>
      <% end %>
    </div>

<!--
  </div>
  <div class="col s4">
    <% if @gamers.blank? %>
      <div class="row center-align">
        <em><h4>No gamers to show</h4></em>
      </div>
    <% else %>
      <div class="row center-align">
        <h4><em>Lastest gamers</em></h4>
      </div>
      <%= render "show_gamers" %>
      <div class="col s12 center-align">
        <%= link_to 'Show all gamers', gamers_path, class: 'waves-effect waves-light btn-large' %>
      </div>
    <% end %>
  </div>
-->
</div>