config/routes.rb
Rails.application.routes.draw do
  resources :gamers do
    member do
      get :friends, :blocks
    end
  end

  resources :friendships,       only: [:create, :destroy]
  resources :requests, only: [:create, :destroy]
  resources :blocks, only: [:create, :destroy]
  resources :gamers, only: [:index, :show, :update, :edit]
  resources :gamers do
    resources :comments
    patch :promote, on: :member
  end

  resources :platforms, only: [:show, :edit, :update]
  resources :games do
    resources :desires, only: [:create, :update, :destroy] do
      patch :accept, on: :member
    end
    patch :rent_back, on: :member
  end
  resources :desires, only: [:index, :destroy, :show]
  resources :titles, only: [:index, :show, :edit, :update]
  resources :queries, only: [:index, :show, :new, :create]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :game_info
  belongs_to :owner, class_name: "User"
  belongs_to :holder, class_name: "User"
  belongs_to :platform, optional: true

  has_many :desires, dependent: :destroy

  validates :state, inclusion: {in: 0..4}
  validates :start_holding, presence: true
  validate :expire_after_hold, :expire_in_rented, :has_platforms

  private
  def expire_after_hold
    if !expire.blank?
      errors.add(:expire, "should be after you hold the game") if expire <= start_holding
    end
  end

  def expire_in_rented
    if expire.blank?
      errors.add(:expire, "should exists if state is rented") if state == 4
    else
      errors.add(:expire, "should not be present if state different from rented") if state != 4
    end
  end

  def has_platforms
    p = Platform.where("api_id IN (?)", game_info.platforms)
    if platform.blank?
      errors.add(:platform, "should exist") unless p.blank?
    else
      errors.add(:platform, "should not exist") if p.blank?
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy, :rent_back]
  before_action :authenticate_user!, except: [:index]
  before_action :set_title, only: [:new, :create]

  def index
    name = params[:name_of_the_game]
    city = params[:city]
    platform = params[:platform]
    state = request.query_string.split('&')
                    .select {|b| b.starts_with?('state')}
                    .map {|b| b.remove('state=')}
                    .reject {|b| b.empty?}

    if params[:gamer].blank?
      @games = Game.all.includes(:game_info, :platform, :holder)
      @games = @games.joins(:holder).where('lower(users.city) ~ ?', city.downcase) unless city.blank?
    else
      @gamer = User.find_by_id(params[:gamer])
      authorize! :read, @gamer
      if @gamer.blank?
        redirect_to games_path, alert: 'Gamer not found'
        return
      end
      @games = @gamer.hold_games.includes(:game_info, :platform, :holder)
      @rented = @gamer.rented.includes(:game_info, :platform, :holder)
      @rented = @rented.joins(:holder).where('lower(users.city) ~ ?', city.downcase) unless city.blank?
      @rented = @rented.joins(:platform).where('lower(platforms.name) ~ ?', platform.downcase) unless platform.blank?
      @rented = @rented.joins(:game_info).where('lower(game_infos.name) ~ ?', name.downcase) unless name.blank?
    end

    @games = @games.where('state IN (?)', state) unless state.blank?
    @games = @games.joins(:platform).where('lower(platforms.name) ~ ?', platform.downcase) unless platform.blank?
    @games = @games.joins(:game_info).where('lower(game_infos.name) ~ ?', name.downcase) unless name.blank?
  end


  def show
    @desires = @game.desires.includes(:user)
  end

  def new
    @game = Game.new
    @platforms = Platform.where("api_id IN (?)", @g_i.platforms)
    @new = true
  end

  def create
    @game = Game.new(new_game_params)
    init_game

    begin
      p = Platform.find_by_id(params[:game][:platform].to_i)
      @game.platform = p
    rescue => e
      logger.error "Rescued from #{e.inspect}, creating new game"
    end

    if @game.save
      redirect_to @game, notice: 'Game was successfully created'
    else
      @platforms = Platform.where("api_id IN (?)", @g_i.platforms)
      render :new
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    authorize! :update, @game
    @game.update(state_game_params)
    respond_to do |format|
      format.js {}
      format.html { redirect_to game_path(@game), notice: 'The status of the game was updated' }
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    authorize! :destroy, @game
    @game.destroy
    redirect_to gamer_url(current_user), notice: 'Game was successfully destroyed'
  end

  def rent_back
    authorize! :rent_back, @game
    expire = @game.expire
    new_params = {
      holder: @game.owner,
      start_holding: Time.now,
      expire: nil,
      state: 0,
      note: 'Back from rent'
    }
    if @game.update(new_params)
      @game.owner.add_point 5
      current_user.add_point Time.now > expire ? 2 : 5
      redirect_to @game, notice: 'The game was returned'
    else
      redirect_to @game, alert: 'Some errors occured while returning the game'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find_by_id(params[:id])
      redirect_to games_path, alert: 'Game doesn\'t exist' unless @game
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_game_params
      params.require(:game).permit(:note)
    end

    def state_game_params
      params.require(:game).permit(:state)
    end

    def set_title
      @g_i = GameInfo.find_by_id(params[:game_info])
      redirect_to titles_path, alert: 'Please select a title' unless @g_i
    end

    def init_game
      @game.update_attributes(
        game_info: @g_i,
        owner: current_user,
        holder: current_user,
        state: 0,
        start_holding: Time.now
      )
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if !@new && game.errors.any?%>
  <div id="error_explanation">
    <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

    <ul>
      <% game.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <input type="hidden" name="game_info" value="<%= @g_i.id %>">
  <% if !@platforms.blank? %>
    <div class="input-field col s12">
      <%= form.select :platform, class: 'icons' do %>
        <option value="" disabled selected>Platforms</option>
        <% @platforms.each do |p| %>
          <option value="<%= p.id %>" class="left circle"
            <% if p.photo.blank? %>
              data-icon="http://materializecss.com/images/sample-1.jpg"
            <% else %>
              data-icon="<%= "https://" + p.photo %>"
            <% end %>
          > <%= p.name %></option>
        <% end %>
      <% end %>
      <label>Please select a platform</label>
    </div>
  <% end %>
  <div class="row">
    <label>Conditions</label>
    <div class="switch">
      <label>
        Used
        <input type="hidden" name="game[note]" value="used">
        <input type="checkbox" name="game[note]" value="new">
        <span class="lever"></span>
        New
      </label>
    </div>
  </div>

  <div class="row">
    <div class="actions">
      <%= form.submit "Add", class: 'waves-effect waves-light btn-large' %>
    </div>
  </div>
<% end %>

app/views/games/_game_card.html.erb
<% card_color = ['green darken-3', 'teal darken-2', 'pink lighten-1', 'blue-grey darken-1', 'orange darken-4'] %>

<% games.each do |game| %>
  <div class="col s12 l4">
    <div class="card small">
      <div class="card-image waves-effect waves-block waves-light">
        <% if game.game_info.cover.blank? %>
        <%= image_tag "game_no_cover.jpg", class: "activator" %>
        <% else %>
        <img src="<%= game.game_info.cover.gsub(/t_thumb/, 't_720p') %>" alt="Photo of the game" class="activator"/>
        <% end %>
      </div>
      <div class="card-content <%= card_color[game.state] %>">
        <span class="card-title activator grey-text text-darken-4 truncate">
          <div class="col s10 truncate activator">
            <%= game.game_info.name %>
          </div>
          <div class="col s2">
            <i class="material-icons">more_vert</i>
          </div>
        </span>
      </div>
      <div class="card-action <%= card_color[game.state] %>">
        <% if can? :read, game %>
          <%= link_to 'Show the game', game_path(game) %>
        <% else %>
          <%= link_to 'Signin for more', new_user_session_path %>
        <% end %>
      </div>
      <div class="card-reveal">
        <span class="card-title grey-text text-darken-4">
          <%= game.game_info.name %>
          <i class="material-icons right">close</i>
        </span>
        <p> <%= get_status(game.state) %></p>
        <p>From <%= format_date(game.start_holding) %></p>
        <p> <%= link_to cap_name(game.holder), gamer_path(game.holder) %></p>
        <p> <%= cap_city(game.holder) %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/games/_game_info.html.erb
<div class="row">
  <div class="col s3">Owner:</div>
  <div class="col s9"> <%= cap_name(game.owner) %> </div>
</div>
<div class="row">
  <div class="col s3">Holder:</div>
  <div class="col s9"> <%= cap_name(game.holder) %> </div>
</div>
<div class="row">
  <div class="col s3">From:</div>
  <div class="col s9"> <%= format_date(game.start_holding) %> </div>
</div>
<% if game.state == 4 %>
  <div class="row">
    <div class="col s3">State:</div>
    <div class="col s9"> Rented</div>
  </div>
  <div class="row">
    <div class="col s3">Until:</div>
    <div class="col s9"> <%= format_date(game.expire) %></div>
  </div>
  <% if Time.now >= game.expire %>
    <div class="row red-text">
      <div class="col s12">
        Delay of <em><%= distance_of_time_in_words(Time.now, game.expire) %></em>
      </div>
    </div>
  <% else %>
    <div class="row green-text">
      <div class="col s12">
        To return in <em><%= distance_of_time_in_words(Time.now, game.expire) %></em>
      </div>
    </div>
  <% end %>
  <% if can? :rent_back, game %>
  <div class="row">
    <div class="col s12">
      <%= link_to 'Return this game', rent_back_game_path(game), {class: 'btn waves-light waves-effect', method: :patch} %>
    </div>
  </div>
  <% end %>
<% else %>
  <div class="row">
    <div class="col s3">Note:</div>
    <div class="col s9"> <%= game.note.capitalize %> </div>
  </div>
  <div class="row">
    <div class="col s3">Status:</div>
    <% if can? :update, game %>
      <div class="col s12 m9" id="up-form">
        <%= form_with(model: game, remote: true, method: :patch) do |form| %>
          <input type="hidden" name="state" value="<%= game.state %>">
          <div class=" input-field col s6">
            <%= form.select :state do %>
              <option value="" disabled>Choose the new state</option>
              <% for i in 0..3 %>
                <option value="<%= i %>" <%= "selected" if game.state == i %> > <%= get_status(i) %></option>
              <% end %>
            <% end %>
          </div>
          <div class="input-field col s6">
            <%= form.submit "Change status", class: 'btn waves-effect waves-light disabled' %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="col s9">
        <%= get_status(game.state) %>
      </div>
    <% end %>
  </div>
<% end %>

<% if can? :destroy, game %>
  <div class="row">
    <div class="col">
      <button class="btn delete-button red">Delete</button>
    </div>
    <div id="delete-confirmation" class="modal">
      <div class="modal-content red lighten-3">
        <h4>Are you sure?</h4>
        <p>If you press the DELETE button this game will be deleted definitly from our databse and it will be impossible to show it again.</p>
      </div>
      <div class="modal-footer red lighten-2">
        <button type="button" class="modal-action modal-close waves-effect waves-green btn">Cancel</button>
        <%= link_to "Delete", game_path(game), method: :delete, class: 'modal-action modal-close waves-effect waves-green btn red' %>
      </div>
    </div>
  </div>
<% end %>

app/views/games/_req_form.html.erb
<% desire.nil? ? desire = Desire.new : nil %>
<% statuses = desire.statuses || [] %>
<% has_desire = statuses.any? %>
<div class="col s12 l3">
  <div class="row"><h6> <%= has_desire ? 'Your request' : 'Make a new request' %></h6></div>
  <%= form_with(model: [ @game, desire ], local: true) do |form| %>
    <div class="row">
      <div class="col s4">
        <p>
          <%= check_box_tag :status1, 1, statuses.include?(1), {class: 'filled-in'} %>
          <%= label_tag :status1, "Sale" %>
        </p>
      </div>
      <div class="col s4">
        <p>
          <%= check_box_tag :status2, 1, statuses.include?(2), {class: 'filled-in'} %>
          <%= label_tag :status2, "Gift" %>
        </p>
      </div>
      <div class="col s4">
        <p>
          <%= check_box_tag :status3, 1, statuses.include?(3), {class: 'filled-in'} %>
          <%= label_tag :status3, "Rent" %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="actions">
        <button class="btn waves-effect waves-light" type="submit" name="action">
          <% if has_desire %>
            Update <i class="material-icons right">update</i>
        </button>
      </div>
    </div>
    <div class="row">
      <%= link_to game_desire_path(@game, desire), method: :delete, class: 'waves-effect waves-green btn red' do %>
        Delete <i class='material-icons right'>delete_forever</i>
      <% end %>
    </div>
          <% else %>
            Save <i class="material-icons right">send</i>
        </button>
      </div>
    </div>
          <% end %>
  <% end %>
</div>

app/views/games/_requests.html.erb
<% my_desire = nil %>
<% is_owner = false %>
<% if can? :accept_request, @game  %>
  <% is_owner = true %>
<% end %>
<div class="row">
  <% if @desires.any? %>
    <% req = [] %>
    <% for i in 0..2 %>
      <% req[i] = @desires.select{|r| r.statuses.include?(i+1)} %>
    <% end %>

    <h6>Total <em><%= pluralize(req.flatten.count, 'request') %></em></h6>
    <div class="col s12 l9">
      <ul id="tabs-swipe-demo" class="tabs tabs-fixed-width">
        <% tabs = ['sales requests', 'gift requests', 'rent requests'] %>
        <% for i in 0..2 %>
          <li class="tab col s3"><a href="#status-<%= i + 1 %>"> <%= tabs[i] %>  (<%= req[i].length %>)</a></li>
        <% end %>
      </ul>
      <% for i in 0..2 %>
        <div id="status-<%= i + 1 %>" class="col s12">
          <% if req[i].empty? %>
            <div class="center-align"><h5>No <%= tabs[i] %> to show</h5></div>
          <% else %>
            <ul class="collection">
              <% req[i].each do |r| %>
                <% r.user == current_user ? my_desire = r : nil %>
                  <li class="collection-item">
                    <div>
                      <div class="chip">
                        <% if r.user.photo.blank? %>
                          <%= image_tag "no_photo.jpg" %>
                        <% else %>
                          <img src="<%= r.user.photo %>" alt="Profile photo">
                        <% end %>
                        <a href= "<%= gamer_path(r.user) %>">
                          <%= cap_name(r.user) %>
                        </a>
                      </div>
                      <% if is_owner %>
                        <%= link_to desire_path(r), class: 'secondary-content' do %>
                          <i class="material-icons">send</i>
                        <% end %>
                      <% end %>
                    </div>
                  </li>
              <% end %>
            </ul>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <div class="col s12 l9">
      <h5>No request for this game</h5>
    </div>
  <% end %>

  <% if can? :desire, @game %>
    <%= render 'req_form', desire: my_desire %>
  <% end %>
</div>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="row">
  <div class="col s12">
  <%= form_tag "/games", method: "get", class: "col s12" do %>
    <% if !@gamer.blank? %>
      <input type="hidden" name="gamer" value="<%= @gamer.id %>">
    <% end %>
    <div class="row">
      <div class="input-field col s12 m6 l4">
        <i class="material-icons prefix">query_builder</i>
        <%= search_field_tag :name_of_the_game %>
        <%= label_tag :name_of_the_game %>
      </div>

      <div class="input-field col s12 m6 l4">
        <i class="material-icons prefix">archive</i>
        <select name="state" multiple>
          <option value="" disabled selected>All statuses</option>
          <option value="0">Owned</option>
          <option value="1">For sale</option>
          <option value="2">For gift</option>
          <option value="3">For rent</option>
          <option value="4">Rented</option>
        </select>
        <label>The status</label>
      </div>

      <div class="col s12 m6 l4 input-field">
        <i class="material-icons prefix">location_searching</i>
        <%= search_field_tag :city %>
        <%= label_tag :city %>
      </div>

      <div class="input-field col s12 m6 l4">
        <%= button_tag class: "btn waves-effect waves-light" do %>
          Search
          <i class="material-icons right">search</i>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
</div>

<div class="row">
  <h6>Results: <em> <%= pluralize(@games.count, 'game') %></em></h6>
</div>
<div class="row">
  <%= render 'game_card', games: @games %>
</div>

<% if !@gamer.blank? %>
  <div class="row">
    <h6>Results: <em> <%= pluralize(@rented.count, 'game') %></em> rented</h6>
  </div>
  <div class="row">
    <%= render 'game_card', games: @rented %>
  </div>
<% end %>

app/views/games/new.html.erb
<div class="row">
  <div class="col s12 l6">
    <div class="row">
      <% if @g_i.cover.blank? %>
        <%= image_tag "game_no_cover.jpg", class: "game-info-img" %>
      <% else %>
        <img src="<%= @g_i.cover.gsub(/t_thumb/, 't_cover_big') %>" alt="photo of the game" class="game-info-img">
      <% end %>
    </div>
    <div class="row">
      <h5> <%= @g_i.name %> </h5>
    </div>
  </div>
  <div class="col s12 l6">
    <%= render 'form', game: @game %>
  </div>
</div>

<div class="row">
  <%= link_to 'Back', title_path(params[:game_info]) %>
</div>

app/views/games/show.html.erb
<div class="row">
  <div class="col s12 l6">
    <div class="row">
      <% if @game.game_info.cover.blank? %>
        <%= image_tag "game_no_cover.jpg", class: "game-info-img" %>
      <% else %>
        <img src="<%= @game.game_info.cover.gsub(/t_thumb/, 't_cover_big') %>" alt="photo of the game" class="game-info-img">
      <% end %>
    </div>
    <div class="row">
      <h5> <%= @game.game_info.name %> </h5>
    </div>
  </div>
  <div class="col s12 l6">
    <%= render 'game_info', game: @game %>
  </div>
</div>

<%= render 'requests' %>

<script type="text/javascript">
  var switchFn = function() {
    var select = $('select');
    var state = $('#up-form input[name="state"]');
    var btn = $('#up-form .btn');
    return function () {
      if (select.val() == state.val()) {
        btn.addClass('disabled');
      } else {
        btn.removeClass('disabled');
      }
    }
  }

  $(document).on('turbolinks:load', function() {
    var fn = switchFn();
    fn();
    $('select').on('change', fn);
    $('form').on('submit', (function() {
      var input = $('#up-form input[name="commit"]');
      var btn = $('#up-form .btn');
      return function() {
        input.val('Updating ...')
        btn.addClass('disabled');
      }
    })());
    $('.delete-button').off('click').on('click', function() {
      $('#delete-confirmation').modal('open');
    });
  });
</script>

app/views/games/update.js.erb
setTimeout(function() {
  $('form input[name="commit"]').val('Change state');
}, 400);

if (<%= @game.errors.count %>) {
  Materialize.toast('Some errors happend', 4000);
} else {
  $('form input[name="state"]').val(<%= @game.state %>);
  Materialize.toast('The status of the game was updated', 4000);
}