config/routes.rb
Rails.application.routes.draw do
  resources :gamers do
    member do
      get :friends, :blocks
    end
  end

  resources :friendships,       only: [:create, :destroy]
  resources :requests, only: [:create, :destroy]
  resources :blocks, only: [:create, :destroy]
  resources :gamers, only: [:index, :show, :update, :edit]
  resources :gamers do
    resources :comments
    patch :promote, on: :member
  end

  resources :platforms, only: [:show, :edit, :update]
  resources :games do
    resources :desires, only: [:create, :update, :destroy] do
      patch :accept, on: :member
    end
    patch :rent_back, on: :member
  end
  resources :desires, only: [:index, :destroy, :show]
  resources :titles, only: [:index, :show, :edit, :update]
  resources :queries, only: [:index, :show, :new, :create]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/gamers_controller.rb
class GamersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :get_gamer, except: [:index]
  before_action :same_gamer, only: [:edit, :update]

  def index
    name = params[:name]
    city = params[:city]

    @gamers = User.all
    @gamers = @gamers.where("lower(name) ~ ?", name.downcase) unless name.blank?
    @gamers = @gamers.where("lower(city) ~ ?", city.downcase) unless city.blank?
    @gamers = @gamers.where("visibility = 't'")
  end

  def show
    @comments = Comment.where("commented_id = ?",@gamer).limit(3)
    @have_commented = Comment.where("commented_id = ? AND commentator_id = ?",@gamer,current_user)
  end

  def edit
  end

  def update
    if @gamer.update_attributes(gamer_params)
      redirect_to gamer_path(@gamer), notice: 'User was succesfully updated'
    else
      render :edit
    end
  end

  def destroy
    authorize! :destroy, @gamer
    @gamer.destroy
    redirect_to gamers_path, notice: 'The gamer I forgot the name was deleted'
  end

  def friends
    @friends = @gamer.friends
    @requests = @gamer.requests
    render 'show_friend'
  end

  def blocks
    @blocked = @gamer.blocking
    render 'show_block'
  end

  def promote
    authorize! :promote, @gamer
    @gamer.make_admin
    redirect_to gamer_path(@gamer), notice: 'This user is now administrator'
  end

  private

    def gamer_params
      params.require(:gamer).permit(:name, :city, :phone,
        :visibility, :photo, :age, :gender)
    end

    def get_gamer
      @gamer = User.find_by_id(params[:id])
      redirect_to gamers_path , alert: "Gamer not found" unless @gamer
    end

    def same_gamer
      redirect_to gamers_path, alert: "You are not allowed to do this action." if current_user != @gamer
    end
end

app/helpers/gamer_helper.rb
module GamerHelper
end

app/views/gamers/_block.html.erb
<%= form_for(current_user.active_blocks.build) do |f| %>
  <div><%= hidden_field_tag :blocked_id, @gamer.id %></div>
  <%= f.submit "Block", class: "btn btn-primary" %>
<% end %>

app/views/gamers/_block_form.html.erb
<% unless current_user == (@gamer) %>
  <div id="block_form">
  <% if current_user.blocking?(@gamer) %>
    <%= render 'unblock' %>
  <% else %>
    <%= render 'block' %>
  <% end %>
  </div>
<% end %>

app/views/gamers/_comments.html.erb
<div class="container" style="margin-left: 12px;">
<% if same_user %>
  <div class="row"><%= link_to 'My comments', gamer_comments_path(current_user) ,class: "btn waves-effect waves-light"%></div>
<% else %>
  <div class="row"><%= link_to 'User\'s comments', gamer_comments_path(@gamer) ,class: "btn waves-effect waves-light"%></div>
  <% if @have_commented.any? %>
    <div class="row"><%= link_to 'Show review', gamer_comment_path(@gamer,@have_commented.first) ,class: "btn waves-effect waves-light"%></div>
  <% else %>
    <div class="row"><%= link_to 'Review user', new_gamer_comment_path(@gamer) ,class: "btn waves-effect waves-light"%></div>
  <% end %>
<% end %>
</div>

app/views/gamers/_friend_form.html.erb
<% unless current_user == @gamer %>
  <div id="friend_form">
  <% if current_user.friends?(@gamer) %>
    <%= render 'unfriend' %>
  <% elsif !current_user.requests?(@gamer) %>
    <%= render 'request' %>
  <% else %>
    Your request is pending
  <% end %>
  </div>
<% end %>

app/views/gamers/_gamers_search.html.erb
<div class="row center-hor">
  <div class="col s12 l10">

  <%= form_tag "/gamers", method: "get", class: "col s12" do %>
    <div class="row">
      <div class="input-field col s6 l4">
        <i class="material-icons prefix">people</i>
        <%= search_field_tag :name %>
        <%= label_tag :name %>
      </div>

      <div class="input-field col s6 l4">
        <i class="material-icons prefix">location_searching</i>
        <%= search_field_tag :city %>
        <%= label_tag :city %>
      </div>

      <div class="input-field col s12 l3">
        <%= button_tag class: "btn waves-effect waves-light" do %>
          Search
          <i class="material-icons right">search</i>
        <% end %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/gamers/_refuse_request.html.erb
<%= form_for(@gamer.passive_requests.find_by(applier_id: applier),
  html: { method: :delete }) do |f| %>
  <div><%= hidden_field_tag :applier_id, applier %></div>
  <%= f.submit "Refuse", class: "btn btn-primary" %>
<% end %>

app/views/gamers/_request.html.erb
<%= form_for(current_user.active_requests.build) do |f| %>
  <div><%= hidden_field_tag :recevier_id, @gamer.id %></div>
  <%= f.submit "Ask friendship", class: "btn btn-primary" %>
<% end %>

app/views/gamers/_show_requests.html.erb
<div class="row center-align">
  <em>
    <h4>
      <% if @requests.blank? %>
    </h4>
  </em>
</div>
      <% else %>
      Pending requests
    </h4>
  </em>
</div>

<div class="row">
<% for applier in @requests %>

<div class="col s12 l4">
  <div class="card blue-grey darken-1">
    <div class="card-profile white-text">
      <div class="valign-wrapper">
        <% if applier.photo.blank? %>
          <%= image_tag "no_photo.jpg", class: "circle responsive-img activator card-profile-image" %>
        <% else %>
          <img src="<%= applier.photo %>" alt="Profile photo" class="circle responsive-img activator card-profile-image">
        <% end %>
        <a class="btn-floating activator waves-effect waves-light darken-2 right">
          <i class="material-icons">expand_less</i>
        </a>
      </div>
      <span class="card-title activator white-text darken-3">
        <%= applier.name.blank? ? "Anomymous" : applier.name.split.map(&:capitalize).join(" ") %>
      </span>
      <p><%= applier.email %></p>
      <p><%= applier.city.blank? ? "World" : applier.city %></p>
    </div>

    <div class="card-reveal">
      <span class="card-title grey-text">
        <%= applier.name.blank? ? "Anomymous" : applier.name.split.map(&:capitalize).join(" ") %>
        <a class="btn-floating activator waves-effect waves-light darken-2 right">
          <i class="material-icons">expand_more</i>
        </a>
      </span>
      <div class="valign-wrapper"><i class="material-icons">email</i> <%= applier.email %> </div>
      <div class="valign-wrapper">
        <i class="material-icons">phone</i>
        <%= applier.phone.blank? ? "_________" : applier.phone %>
      </div>
      <div class="valign-wrapper">
        <i class="material-icons">star_half</i>
        <%= applier.avg_vote %>
      </div>
    </div>
    <div class="card-action">
      <div class="row">
        <div class="col s6">
          <%= link_to "Visit profile", gamer_path(applier) %>
        </div>
      </div>
      <div class="row">
        <div class="col s6">
          <%= render 'accept_request', applier: applier.id %>
        </div>
        <div class="col right-align s6">
          <%= render 'refuse_request', applier: applier.id %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>
</div>
<% end %>

app/views/gamers/_unblock.html.erb
<%= form_for(current_user.active_blocks.find_by(blocked_id: @gamer.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unblock", class: "btn" %>
<% end %>

app/views/gamers/_unfriend.html.erb
<% if current_user.active_friendships.find_by(friended_id: @gamer.id) != nil %>
  <%= form_for(current_user.active_friendships.find_by(friended_id: @gamer.id),
    html: { method: :delete }) do |f| %>
    <%= f.submit "unfriend", class: "btn" %>
  <% end %>
<% else %>
  <%= form_for(current_user.passive_friendships.find_by(friender_id: @gamer.id),
    html: { method: :delete }) do |f| %>
    <%= f.submit "unfriend", class: "btn" %>
  <% end %>
<% end %>

app/views/gamers/edit.html.erb
<div class="container">
  <div class="row center-align"><h3>Edit profile</h3></div>
  <div class="row">
    <div class="col s12 l6">
    <% if @gamer.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@gamer.errors.count, "error") %>. Your profile has not been updated because:</h2>

        <ul>
        <% @gamer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <%= form_for(@gamer, as: :gamer, method: :patch, url: gamer_path(@gamer)) do |f| %>

      <div class="row">
        <div class="input-field">
          <i class="material-icons prefix">add_a_photo</i>
          <%= f.text_field :photo %>
          <%= f.label :photo, "Insert photo URL" %>
        </div>
      </div>

      <div class="row">
        <div class="input-field">
          <i class="material-icons prefix">face</i>
          <%= f.text_field :name%>
          <%= f.label :name %>
        </div>
      </div>

      <div class="row">
        <div class="input-field">
          <i class="material-icons prefix">cake</i>
          <%= f.number_field :age%>
          <%= f.label :age, "Insert your age"%>
        </div>
      </div>

      <div class="row">
        <p>
          <i class="material-icons prefix">wc</i>
          <%= f.radio_button 'gender', 'm' , class: 'with-gap'%>
          <%= f.label :gender, "Male", value: 'm'%>
          <%= f.radio_button 'gender', 'f', class: 'with-gap' %>
          <%= f.label :gender, "Female", value: 'f' %>
        </p>
      </div>

      <div class="row">
        <div class="input-field">
          <i class="material-icons prefix">location_city</i>
          <%= f.text_field :city %>
          <%= f.label :city, "Insert your city"%>
        </div>
      </div>

      <div class="row">
        <div class="input-field">
          <i class="material-icons prefix">local_phone</i>
          <%= f.number_field :phone%>
          <%= f.label :phone, "Insert your phone number" %>
        </div>
      </div>

      <div class="row">
        <p>
          <%= f.check_box :visibility, class: 'filled-in' %>
          <%= f.label :visibility, "Visibile profile?" %>
        </p>
      </div>

      <div class="row">
        <div class="actions">
          <%= f.submit "Save changes", class: 'waves-effect waves-light btn-large' %>
        </div>
      </div>
      <% end %>
    </div>

  </div>
</div>

<script>
  $(document).on('turbolinks:load', function(){
    Materialize.updateTextFields();
  });
</script>

app/views/gamers/index.html.erb
<%= render 'gamers_search' %>

<div class="row center-align">
  <em>
    <h4>
      <% if @gamers.blank? %>
      No gamers
    </h4>
  </em>
</div>
      <% else %>
      Gamers
    </h4>
  </em>
</div>
<div class="row">
<% for gamer in @gamers %>
  <div class="col s12 l4">
    <div class="card blue-grey darken-1">
      <div class="card-profile white-text">
        <% hideProfile = (current_user != gamer) && !gamer.visibility %>
        <div class="valign-wrapper">
          <% if gamer.photo.blank? %>
            <%= image_tag "no_photo.jpg", class: "circle responsive-img activator card-profile-image" %>
          <% else %>
            <img src="<%= gamer.photo %>" alt="Profile photo" class="circle responsive-img activator card-profile-image">
          <% end %>
          <a class="btn-floating activator waves-effect waves-light darken-2 right">
            <i class="material-icons">expand_less</i>
          </a>
        </div>
        <span class="card-title activator white-text darken-3">
          <%= cap_name(gamer) %>
        </span>
        <p><%= cap_email(gamer) %></p>
        <p><%= cap_city(gamer) %></p>
      </div>

      <div class="card-reveal">
        <span class="card-title grey-text">
          <%= cap_name(gamer) %>
          <a class="btn-floating activator waves-effect waves-light darken-2 right">
            <i class="material-icons">expand_more</i>
          </a>
        </span>
        <div class="valign-wrapper"><i class="material-icons">email</i> <%= cap_email(gamer) %> </div>
        <div class="valign-wrapper">
          <i class="material-icons">phone</i>
          <%= cap_phone(gamer) %>
        </div>
        <div class="valign-wrapper">
          <i class="material-icons">star_half</i>
          <%= gamer.avg_vote %>
        </div>
      </div>

      <div class="card-action">
        <% if can? :read, gamer %>
          <%= link_to "Visit profile", gamer_path(gamer) %>
        <% else %>
          <%= link_to "Log in to view more", new_user_session_path %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>
<% end %>

app/views/gamers/show.html.erb
  <% same_user = user_signed_in? && @gamer.id == current_user.id %>
  <% frnd = @gamer.friends?(current_user) %>


<div class="USER z-depth-1 col row">
  <div class="INFO_AND_PHOTO row">
    <table style="margin-left: 10px;">

      <td>
        <table>
<!-- non si puo mettere edit name con link edit profile quando non e impostato??? -->
          <tr><td><i class="material-icons prefix">face</i></td><td><b>Name:</b></td><td><%= cap_name_i(@gamer, frnd) %></td></tr>
          <tr><td><i class="material-icons prefix">cake</i></td><td><b>Age:</b></td><td><%= cap_age(@gamer, frnd) %></td></tr>
          <tr><td><i class="material-icons prefix">wc</i></td><td><b>Gender:</b></td><td><%= cap_gender(@gamer, frnd) %></td></tr>
          <tr><td><i class="material-icons prefix">location_city</i></td><td><b>City:</b></td><td><%= cap_city_i(@gamer, frnd) %></td></tr>
          <tr><td><i class="material-icons prefix">local_phone</i></td><td><b>Cell:</b></td><td><%= cap_phone_i(@gamer, frnd) %></td></tr>
          <tr><td><i class="material-icons prefix">email</i></td><td><b>E-mail:</b></td><td><%= cap_email_i(@gamer, frnd) %></td></tr>
        </table>
      </td>

      <td>
        <div class="col s3 l5">
          <% if @gamer.photo.blank? %>
            <%= image_tag "no_photo.jpg" , class: "responsive-img"%>
          <% else %>
            <img class="responsive-img" src="<%= @gamer.photo %>"/>
          <% end %>
        </div>
      </td>
    </table>
    <div style="margin-left: 20px;">
    <% if same_user %>
      <%= link_to "Edit your profile", edit_gamer_url(current_user) ,class: "btn waves-effect waves-light"%>
    <% end %>
    </div>
  </div>
  <div class="VALUTATION row" style="margin-left: 10px;">

    <table style="max-width: fit-content;">
      <tr><td><i class="material-icons prefix">extension</i></td><td><b>Gamer Points:</b></td><td><%= @gamer.points %></td></tr>
      <tr><td><i class="material-icons prefix">star</i></td><td><b>Valutation:</b></td><td><%= @gamer.avg_vote %> stars </td></tr>
    </table>
     <%= render "comments", same_user: same_user %>
  </div>
</div>
<% if same_user %>
  <div class="row">
    <%= link_to 'Show your game requests', desires_path %>
  </div>
<% else %>
  <% if @gamer.admin? %>
    <div class="row right-align"><div class="btn">Administrator</div></div>
  <% end %>
<% end %>

<% if can?(:promote, @gamer) %>
  <div class="row right-align">
    <button class="btn delete-user-button red">Delete this account</button>
    <button class="btn promote-user-button">Promote to admin</button>
  </div>
  <div id="delete-user-confirmation" class="modal">
    <div class="modal-content red lighten-3">
      <h4>Are you sure?</h4>
      <p>If you press the DELETE button this gamer and all the resourses associated
        with it will be deleted definitly from our databse and will be impossible to show them again.</p>
    </div>
    <div class="modal-footer red lighten-2">
      <button type="button" class="modal-action modal-close waves-effect waves-green btn">Cancel</button>
      <%= link_to "Delete", gamer_path(@gamer), method: :delete, class: 'modal-action modal-close waves-effect waves-green btn red' %>
    </div>
  </div>
  <div id="promote-user-confirmation" class="modal">
    <div class="modal-content green lighten-3">
      <h4>Are you sure?</h4>
      <p>If you press Promote this user will become administrator and it can perform
        action that can delete or modify resources.</p>
    </div>
    <div class="modal-footer green lighten-2">
      <button type="button" class="modal-action modal-close waves-effect waves-green btn">Cancel</button>
      <%= link_to 'Promote', promote_gamer_path(@gamer), {method: :patch, class: 'btn wave-effect wave-light'} %>
    </div>
  </div>
<% end %>

<div class="GAMES-COMMENTS-FRIENDS z-depth-1 row">
  <div class="col s12 l6" style="margin-left: 10px;">
    <% games = @gamer.hold_games.last(5) %>
    <% if games.blank? %>
      <div class="row">No games to show</div>
      <div class="row">
        <% if same_user %>
          <%= link_to "Start adding a new game", titles_path ,class: "btn waves-effect waves-light"%>
        <% end %>
      </div>
    <% else %>
      <div class="row">Games <%= same_user ? "you posses" : "" %></div>
      <div class="row">
        <% games.each do |game| %>
          <a href="<%= game_path(game) %>">
            <div class="chip col game-title" style="min-width: max-content;">
              <div class="truncate">
                <%= game.game_info.name %>
              </div>
            </div>
          </a>
        <% end %>
      </div>
      <div class="row">
        <div class="col s6">
          <%= link_to "Show collection", games_path(gamer: @gamer.id) %>
        </div>
        <div class="col s6">
          <% if same_user %>
            <%= link_to "Add a new game", titles_path %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>

    <div class="FRIENDS col s12 l6" style="margin-left: -10px;">
        <div class="row center-align">
          <%= render 'shared/stats' %>
          <% if current_user == @gamer %>
            <%= render 'shared/blocked_stats' %>
          <% end %>
        </div>
        <div class="row">
          <div class="col s6">
            <%= render 'friend_form' %>
          </div>
          <div class="col s6">
            <%= render 'block_form' %>
          </div>
        </div>
        <%= render 'friends_show_min' %>
    </div>
  </div>
</div>

<script type="text/javascript">
$(document).on('turbolinks:load', function() {
  $('.delete-user-button').off('click').on('click', function() {
    $('#delete-user-confirmation').modal('open');
  });
  $('.promote-user-button').off('click').on('click', function() {
    $('#promote-user-confirmation').modal('open');
  });
});
</script>

app/views/gamers/show_block.html.erb
<div class="row center-align">
  <em>
    <h4>
      <% if @blocked.blank? %>
      No blocked users to show
    </h4>
  </em>
</div>
      <% else %>
      Blocked users
    </h4>
  </em>
</div>

<% for blocked in @blocked %>

<div class="col s12 l4">
  <div class="card blue-grey darken-1">
    <div class="card-profile white-text">
      <div class="valing-wrapper">
        <% if blocked.photo.blank? %>
          <%= image_tag "no_photo.jpg", class: "circle responsive-img activator card-profile-image" %>
        <% else %>
          <img src="<%= friend.photo %>" alt="Profile photo" class="circle responsive-img activator card-profile-image">
        <% end %>
        <a class="btn-floating activator waves-effect waves-light darken-2 right">
          <i class="material-icons">expand_less</i>
        </a>
      </div>
      <span class="card-title activator white-text darken-3">
        <%= blocked.name.blank? ? "Anomymous" : blocked.name.split.map(&:capitalize).join(" ") %>
      </span>
      <p><%= blocked.email %></p>
      <p><%= blocked.city.blank? ? "World" : blocked.city %></p>
    </div>

    <div class="card-reveal">
      <span class="card-title grey-text">
        <%= blocked.name.blank? ? "Anomymous" : blocked.name.split.map(&:capitalize).join(" ") %>
        <a class="btn-floating activator waves-effect waves-light darken-2 right">
          <i class="material-icons">expand_more</i>
        </a>
      </span>
      <div class="valign-wrapper"><i class="material-icons">email</i> <%= blocked.email %> </div>
      <div class="valign-wrapper">
        <i class="material-icons">phone</i>
        <%= blocked.phone.blank? ? "_________" : blocked.phone %>
      </div>
      <div class="valign-wrapper">
        <i class="material-icons">star_half</i>
        <%= blocked.avg_vote %>
      </div>
    </div>
    <div class="card-action">
      <%= link_to "Visit profile", gamer_path(blocked) %>
    </div>
  </div>
</div>
<% end %>

<% end %>