config/routes.rb
Rails.application.routes.draw do
  resources :gamers do
    member do
      get :friends, :blocks
    end
  end

  resources :friendships,       only: [:create, :destroy]
  resources :requests, only: [:create, :destroy]
  resources :blocks, only: [:create, :destroy]
  resources :gamers, only: [:index, :show, :update, :edit]
  resources :gamers do
    resources :comments
    patch :promote, on: :member
  end

  resources :platforms, only: [:show, :edit, :update]
  resources :games do
    resources :desires, only: [:create, :update, :destroy] do
      patch :accept, on: :member
    end
    patch :rent_back, on: :member
  end
  resources :desires, only: [:index, :destroy, :show]
  resources :titles, only: [:index, :show, :edit, :update]
  resources :queries, only: [:index, :show, :new, :create]
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row center">
      <div class="col l4 s12">
        <h5 class="white-text">About</h5>
        <p class="grey-text text-lighten-4">A site for sell, buy and trade your games and consoles.</p>
      </div>
      <div class="col l3 offset-l1 s12">
        <h5 class="white-text">Creators</h5>
        <ul>
          <li><i class="material-icons">adb</i><a class="grey-text text-lighten-3" href="https://github.com/19ion91/">  Ion</a></li>
          <li><i class="material-icons">android</i><a class="grey-text text-lighten-3" href="https://github.com/isgj/">  Isgj</a></li>
          <li><i class="material-icons">bug_report</i><a class="grey-text text-lighten-3" href="https://github.com/Sby-EasyStuff/">  Sby</a></li>
        </ul>
      </div>
      <div class="col l4 s12">
        <h5 class="white-text">Share us</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A3000%2F&amp;src=sdkpreparse">Facebook</a></li>
          <li><a class="grey-text text-lighten-3" href="https://plus.google.com/share?url=http://localhost:3000/" onclick="javascript:window.open(this.href,
            '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;">Google +</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © <%= Time.current.year %> Copyright Text
    </div>
  </div>
</footer>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/it_IT/sdk.js#xfbml=1&version=v2.11';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_header.html.erb
<header>
  <div class="navbar-fixed">
    <% if user_signed_in? %>
      <%= render 'layouts/profile_links', data: 'profile-menu' %>
      <%= render 'layouts/profile_links', data: 'mob-profile-menu' %>
    <% end %>

    <nav>
      <div class="nav-wrapper">
        <%= link_to 'GameExchange', root_path, class: 'brand-logo' %>
        <a href="#!" data-activates="mobile-menu" class="button-collapse"><i class="material-icons">menu</i></a>

        <ul class="right hide-on-med-and-down">
          <%= render 'layouts/menu_links', data: 'profile-menu' %>
        </ul>
        <ul class="side-nav" id="mobile-menu">
          <%= render 'layouts/menu_links', data: 'mob-profile-menu' %>
        </ul>

      </div>
    </nav>
  </div>
</header>

app/views/layouts/_menu_links.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Titles', titles_path %></li>
<% end %>
<li><%= link_to 'Games', games_path %></li>
<li><%= link_to 'Gamers', gamers_path %></li>
<% if user_signed_in? %>
  <li>
    <a class="dropdown-button" href="#!" data-activates="<%= data %>">
      <%= current_user.name.blank? ? "Your profile" : current_user.name.split.map(&:capitalize).join(" ") %>
      <i class="material-icons right">arrow_drop_down</i>
    </a>
  </li>
<% else %>
  <% if request.fullpath != new_user_registration_path %>
    <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <% end %>
  <% if request.fullpath != new_user_session_path %>
    <li><%= link_to 'Log in', new_user_session_path %></li>
  <% end %>
<% end %>

app/views/layouts/_oauth.html.erb
<div class="col s12 l6 center-align">
  <div class="row col s12"><h5><em>Or</em></h5></div>
  <div class="row col s12">
    <%= link_to 'Sign in with Google', user_google_omniauth_authorize_path, class: 'waves-effect waves-light btn-large red' %>
  </div>
  <div class="row col s12">
    <%= link_to 'Sign in with Facebook', user_facebook_omniauth_authorize_path, class: 'waves-effect waves-light btn-large blue' %>
  </div>
</div>

app/views/layouts/_profile_links.html.erb
<ul id="<%= data %>" class="dropdown-content">
  <li><%= link_to 'Add a game', titles_path %></li>
  <li><%= link_to 'Show profile', gamer_path(current_user) %></li>
  <li><%= link_to 'Edit profile', edit_gamer_path(current_user)%></li>
  <li class="divider"></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li class="divider"></li>
  <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameExchange</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="row">
      <div>
    <% if notice %>
        <div class="alert">
          <div class="chip green white-text z-depth-3">
            <%= notice %>
            <i class="close material-icons">close</i>
          </div>
        </div>
    <% end %>
    <% if alert %>
        <div class="alert">
          <div class="chip red white-text z-depth-3">
            <%= alert %>
            <i class="close material-icons">close</i>
          </div>
        </div>
    <% end %>
      </div>
    </div>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <%= render 'layouts/footer' %>

    <script type="text/javascript">
    $(document).on('turbolinks:load', function(){
      setTimeout(function(){
        $('.alert').remove();
      }, 5000);
     })
    </script>
    <% if cookies && cookies[:eat_cookie] != 'gnam' %>
      <div class="toast toast-cookie-banner">
        <div>
          In order to make this web app work we use <a href="https://en.wikipedia.org/wiki/HTTP_cookie">cookies</a>.
          But don't be affraid our cookies are gluten-free, sugar-free and we do not use palm oil.
          <button class="btn-flat" id="accept-cookie"><strong>Agree</strong></button>
        </div>
      </div>
    <% end %>
  </body>
</html>